# Generated by Django 5.2.6 on 2025-09-29 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аниме')),
                ('old_name', models.CharField(max_length=255, verbose_name='Название на оригинале')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Вышло', 'Завершён'), ('Релиз', 'Релиз'), ('Выходит', 'Выходит')], default=('Выходит', 'Выходит'), verbose_name='Статус')),
                ('episode_duration', models.TimeField(max_length=4, verbose_name='Длительность эпизода')),
                ('quantity_of_episodes', models.IntegerField(verbose_name='Количество эпизодов')),
                ('release_date', models.DateField(verbose_name='Дата выхода первой серии')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=4, verbose_name='Номер эпизода')),
                ('name', models.CharField(max_length=100, verbose_name='Название эпизода')),
                ('Release_date', models.DateField(verbose_name='Дата выхода')),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.anime')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизод',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='anime_app_g_name_7e3730_idx')],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='id_genres',
            field=models.ManyToManyField(to='anime_app.genres'),
        ),
        migrations.CreateModel(
            name='studios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название студии')),
            ],
            options={
                'verbose_name': 'Студии',
                'verbose_name_plural': 'Студии',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='anime_app_s_name_0f81f5_idx')],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='id_studios',
            field=models.ManyToManyField(to='anime_app.studios'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=150, verbose_name='Почта')),
                ('description', models.TextField(max_length=300, verbose_name='Описание профиля')),
                ('last_login_time', models.DateTimeField(verbose_name='Время последнего входа')),
                ('account_creation_date', models.DateField(verbose_name='Дата создания аккаунта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='anime_app_u_name_0f453a_idx')],
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('Release_date', models.DateField(verbose_name='Время создания')),
                ('id_anime', models.ManyToManyField(to='anime_app.anime')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.users')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['id_user'],
            },
        ),
        migrations.CreateModel(
            name='playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название плейлиста')),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.anime')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.users')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='viewing_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.episodes')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.users')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'История просмотра',
                'ordering': ['id_user'],
            },
        ),
        migrations.AddIndex(
            model_name='episodes',
            index=models.Index(fields=['name'], name='anime_app_e_name_8d61f1_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['name'], name='anime_app_a_name_5e9f51_idx'),
        ),
        migrations.AddConstraint(
            model_name='anime',
            constraint=models.UniqueConstraint(fields=('name', 'description'), name='unique_name_description'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['id_user'], name='anime_app_r_id_user_d58eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='playlists',
            index=models.Index(fields=['name'], name='anime_app_p_name_75a692_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing_history',
            index=models.Index(fields=['id_user'], name='anime_app_v_id_user_7f2b5c_idx'),
        ),
    ]
