# Generated by Django 5.2.6 on 2025-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='description',
            field=models.TextField(default='Описание отсутствует', verbose_name='Описание жанра'),
        ),
        migrations.AddField(
            model_name='studios',
            name='adress',
            field=models.CharField(default='', verbose_name='Адрес студии'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='number',
            field=models.IntegerField(verbose_name='Номер эпизода'),
        ),
    ]
