# Generated by Django 5.2.8 on 2025-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_genres_description_studios_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='anime_posters/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
