# Generated by Django 5.2.8 on 2025-11-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0003_anime_poster_anime_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='release_date',
        ),
    ]
