# Generated by Django 5.2.8 on 2025-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_remove_anime_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episode_duration',
            field=models.IntegerField(verbose_name='Длительность эпизода (в минутах)'),
        ),
    ]
