# Generated by Django 5.2.8 on 2025-11-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0005_alter_anime_episode_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1, verbose_name='Сезон')),
                ('episode_number', models.IntegerField(verbose_name='Номер серии')),
                ('title', models.CharField(max_length=200, verbose_name='Название серии')),
                ('video_file', models.FileField(blank=True, upload_to='episodes/', verbose_name='Видео файл')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
