# Generated by Django 5.2.8 on 2025-11-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0006_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing_history',
            name='id_episodes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.episode'),
        ),
        migrations.DeleteModel(
            name='episodes',
        ),
    ]
