# Generated by Django 5.2.8 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0007_alter_viewing_history_id_episodes_delete_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.CharField(choices=[('Фильм', 'Фильм'), ('Сериал', 'Сериал')], default=('Сериал', 'Сериал'), verbose_name='Категория'),
        ),
    ]
