# Generated by Django 5.2.8 on 2025-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0008_anime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='content_rating',
            field=models.IntegerField(default=0, verbose_name='Оценка контента'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='design_rating',
            field=models.IntegerField(default=0, verbose_name='Оценка дизайна'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='performance_rating',
            field=models.IntegerField(default=0, verbose_name='Оценка производительности'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='usability_rating',
            field=models.IntegerField(default=0, verbose_name='Оценка удобства'),
        ),
    ]
