# Generated by Django 6.0.3 on 2026-03-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0009_reviews_content_rating_reviews_design_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.CharField(choices=[('Фильм', 'Фильм'), ('Сериал', 'Сериал')], default=('Сериал', 'Сериал'), max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Вышло', 'Завершён'), ('Релиз', 'Релиз'), ('Выходит', 'Выходит')], default=('Выходит', 'Выходит'), max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название плейлиста'),
        ),
        migrations.AlterField(
            model_name='studios',
            name='adress',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес студии'),
        ),
        migrations.AlterField(
            model_name='studios',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название студии'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.anime', verbose_name='Аниме')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'unique_together': {('id_user', 'id_anime')},
            },
        ),
    ]
